// Shadow Run Scorecard: embedded data.
// SYNTHETIC DATA. Every shipper, facility, reference number and load is made up.
// Each load has the tender excerpt the agent read, the agent's record and the rep's record.
// The rep record is written the way a TMS export often looks (upper case, MM/DD/YYYY, 0800).
(function (root) {
  "use strict";
  const SHADOW_RUN_DATA = {
    label: "Synthetic data",
    scenario: "A fictional mid-size freight broker is two weeks into a shadow run of an AI order-entry agent. Shipper tenders arrive as a PDF, an email body or a spreadsheet. The agent extracts each load, and reps still key the same load into the TMS by hand.",
    tmsTimeZone: "Central",
    shippers: [
      {"id":"A","name":"Shipper A","format":"Spreadsheet"},
      {"id":"B","name":"Shipper B","format":"Email"},
      {"id":"C","name":"Shipper C","format":"PDF"},
      {"id":"D","name":"Shipper D","format":"PDF"},
      {"id":"E","name":"Shipper E","format":"Email"},
      {"id":"F","name":"Shipper F","format":"Spreadsheet"},
    ],
    loads: [
      {
        load_id: "A-01", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 2",
          "PO 31041 | Pickup 09/14/2026 07:00 CT | Shipper A Plant, Rockford IL",
          "Deliver Fairmont Grocers DC, Des Moines IA | appt 13:00 CT",
          "53' Dry Van | Weight 38400 | Unit LB | Canned vegetables",
        ],
        agent: {"reference":"PO-31041","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-14","pickup_appt":"07:00","delivery_facility":"Fairmont Grocers DC, Des Moines IA","delivery_appt":"13:00","equipment":"53' Dry Van","weight_lbs":38400,"stops":["Rockford IL","Des Moines IA"],"commodity":"Canned vegetables"},
        rep: {"reference":"PO-31041","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/14/2026","pickup_appt":"0700","delivery_facility":"FAIRMONT GROCERS DC, DES MOINES IA","delivery_appt":"1300","equipment":"53' DRY VAN","weight_lbs":38400,"stops":["ROCKFORD IL","DES MOINES IA"],"commodity":"CANNED VEGETABLES"},
      },
      {
        load_id: "A-02", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 3",
          "PO 31042 | Pickup 09/14/2026 08:00 CT | Shipper A Plant, Rockford IL",
          "Deliver Prairie Pantry DC, Omaha NE | window 08:00-14:00 CT",
          "53' Dry Van | Weight 41250 | Unit LB | Canned vegetables",
        ],
        agent: {"reference":"PO-31042","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-14","pickup_appt":"08:00","delivery_facility":"Prairie Pantry DC, Omaha NE","delivery_appt":"08:00-14:00","equipment":"53' Dry Van","weight_lbs":41250,"stops":["Rockford IL","Omaha NE"],"commodity":"Canned vegetables"},
        rep: {"reference":"PO-31042","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/14/2026","pickup_appt":"0800","delivery_facility":"PRAIRIE PANTRY DC, OMAHA NE","delivery_appt":"0800-1400","equipment":"53' DRY VAN","weight_lbs":41250,"stops":["ROCKFORD IL","OMAHA NE"],"commodity":"CANNED VEGETABLES"},
      },
      {
        load_id: "A-03", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 4",
          "PO 31043 | Pickup 09/15/2026 06:30 CT | Shipper A Plant, Rockford IL",
          "Deliver Bluestem Market DC, Kansas City MO | appt 12:00 CT",
          "53' Dry Van | Weight 36800 | Unit LB | Pet food",
        ],
        agent: {"reference":"PO-31043","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-15","pickup_appt":"06:30","delivery_facility":"Bluestem Market DC, Kansas City MO","delivery_appt":"12:00","equipment":"53' Dry Van","weight_lbs":36800,"stops":["Rockford IL","Kansas City MO"],"commodity":"Pet food"},
        rep: {"reference":"PO-31043","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/15/2026","pickup_appt":"0630","delivery_facility":"BLUESTEM MARKET DC, KANSAS CITY MO","delivery_appt":"1200","equipment":"53' DRY VAN","weight_lbs":36800,"stops":["ROCKFORD IL","KANSAS CITY MO"],"commodity":"PET FOOD"},
      },
      {
        load_id: "A-04", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 5",
          "PO 31044 | Pickup 09/16/2026 09:00 CT | Shipper A Plant, Rockford IL",
          "Deliver Riverbend Supply, St. Louis MO | appt 15:00 CT",
          "53' Dry Van | Weight 40100 | Unit LB | Dry pasta",
        ],
        agent: {"reference":"PO-31044","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-16","pickup_appt":"09:00","delivery_facility":"Riverbend Supply, St. Louis MO","delivery_appt":"15:00","equipment":"53' Dry Van","weight_lbs":40100,"stops":["Rockford IL","St. Louis MO"],"commodity":"Dry pasta"},
        rep: {"reference":"PO-31044 ","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/16/2026","pickup_appt":"0900","delivery_facility":"RIVERBEND SUPPLY, ST. LOUIS MO","delivery_appt":"1500","equipment":"53' DRY VAN","weight_lbs":40100,"stops":["ROCKFORD IL","ST. LOUIS MO"],"commodity":"DRY PASTA"},
      },
      {
        load_id: "A-05", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 6",
          "PO 31045 | Pickup 09/17/2026 07:30 CT | Shipper A Plant, Rockford IL",
          "Deliver Northline Hardware DC, Madison WI | window 06:00-10:00 CT",
          "53' Dry Van | Weight 22950 | Unit LB | Pet food",
        ],
        agent: {"reference":"PO-31045","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-17","pickup_appt":"07:30","delivery_facility":"Northline Hardware DC, Madison WI","delivery_appt":"06:00-10:00","equipment":"53' Dry Van","weight_lbs":22950,"stops":["Rockford IL","Madison WI"],"commodity":"Pet food"},
        rep: {"reference":"PO-31045","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/17/2026","pickup_appt":"0730","delivery_facility":"NORTHLINE HARDWARE DC, MADISON WI","delivery_appt":"0600-1000","equipment":"53' DRY VAN","weight_lbs":22950,"stops":["ROCKFORD IL","MADISON WI"],"commodity":"PET FOOD"},
      },
      {
        load_id: "A-06", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 7",
          "PO 31046 | Pickup 09/18/2026 08:00 CT | Shipper A Plant, Rockford IL",
          "Deliver Fairmont Grocers DC, Des Moines IA | appt 14:00 CT",
          "53' Dry Van | Weight 39900 | Unit LB | Canned vegetables",
        ],
        agent: {"reference":"PO-31046","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-18","pickup_appt":"08:00","delivery_facility":"Fairmont Grocers DC, Des Moines IA","delivery_appt":"14:00","equipment":"53' Dry Van","weight_lbs":39900,"stops":["Rockford IL","Des Moines IA"],"commodity":"Canned vegetables"},
        rep: {"reference":"PO-31046","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/18/2026","pickup_appt":"0800","delivery_facility":"FAIRMONT GROCERS DC, DES MOINES IA","delivery_appt":"1400","equipment":"53' DRY VAN","weight_lbs":39900,"stops":["ROCKFORD IL","DES MOINES IA"],"commodity":"CANNED VEGETABLES"},
      },
      {
        load_id: "A-07", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 8",
          "PO 31047 | Pickup 09/21/2026 10:00 CT | Shipper A Plant, Rockford IL",
          "Deliver Kestrel Home DC, Nashville TN | window 07:00-11:00 CT",
          "53' Dry Van | Weight 35400 | Unit LB | Dry pasta",
        ],
        agent: {"reference":"PO-31047","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-21","pickup_appt":"10:00","delivery_facility":"Kestrel Home DC, Nashville TN","delivery_appt":"07:00-11:00","equipment":"53' Dry Van","weight_lbs":35400,"stops":["Rockford IL","Nashville TN"],"commodity":"Dry pasta"},
        rep: {"reference":"PO-31047","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/20/2026","pickup_appt":"1000","delivery_facility":"KESTREL HOME DC, NASHVILLE TN","delivery_appt":"0700-1100","equipment":"53' DRY VAN","weight_lbs":35400,"stops":["ROCKFORD IL","NASHVILLE TN"],"commodity":"DRY PASTA"},
        disputed: [{"field":"pickup_date","note":"Tender says 09/21/2026; the agent matches it and the rep keyed 09/20/2026."}],
      },
      {
        load_id: "A-08", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 9",
          "PO 31048 | Pickup 09/21/2026 07:00 CT | Shipper A Plant, Rockford IL",
          "Deliver Prairie Pantry DC, Omaha NE | appt 13:30 CT",
          "53' Dry Van | Weight 42000 | Unit LB | Canned soup",
        ],
        agent: {"reference":"PO-31048","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-21","pickup_appt":"07:00","delivery_facility":"Prairie Pantry DC, Omaha NE","delivery_appt":"13:30","equipment":"53' Dry Van","weight_lbs":42000,"stops":["Rockford IL","Omaha NE"],"commodity":"Canned soup"},
        rep: {"reference":"PO-31048 ","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/21/2026","pickup_appt":"0700","delivery_facility":"PRAIRIE PANTRY DC, OMAHA NE","delivery_appt":"1330","equipment":"53' DRY VAN","weight_lbs":42000,"stops":["ROCKFORD IL","OMAHA NE"],"commodity":"CANNED SOUP"},
      },
      {
        load_id: "A-09", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 10",
          "PO 31049 | Pickup 09/22/2026 06:00 CT | Shipper A Plant, Rockford IL",
          "Deliver Bluestem Market DC, Kansas City MO | appt 10:00 CT",
          "53' Dry Van | Weight 37750 | Unit LB | Pet food",
        ],
        agent: {"reference":"PO-31049","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-22","pickup_appt":"06:00","delivery_facility":"Bluestem Market DC, Kansas City MO","delivery_appt":"10:00","equipment":"53' Dry Van","weight_lbs":37750,"stops":["Rockford IL","Kansas City MO"],"commodity":"Pet food"},
        rep: {"reference":"PO-31049","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/22/2026","pickup_appt":"0600","delivery_facility":"BLUESTEM MARKET DC, KANSAS CITY MO","delivery_appt":"1000","equipment":"53' DRY VAN","weight_lbs":37750,"stops":["ROCKFORD IL","KANSAS CITY MO"],"commodity":"PET FOOD"},
      },
      {
        load_id: "A-10", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 11",
          "PO 31050 | Pickup 09/23/2026 08:30 CT | Shipper A Plant, Rockford IL",
          "Deliver Riverbend Supply, St. Louis MO | window 08:00-12:00 CT",
          "53' Dry Van | Weight 33600 | Unit LB | Canned soup",
        ],
        agent: {"reference":"PO-31050","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-23","pickup_appt":"08:30","delivery_facility":"Riverbend Supply, St. Louis MO","delivery_appt":"08:00-12:00","equipment":"53' Dry Van","weight_lbs":33600,"stops":["Rockford IL","St. Louis MO"],"commodity":"Canned soup"},
        rep: {"reference":"PO-31050","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/23/2026","pickup_appt":"0830","delivery_facility":"RIVERBEND SUPPLY, ST. LOUIS MO","delivery_appt":"0800-1200","equipment":"53' DRY VAN","weight_lbs":33600,"stops":["ROCKFORD IL","ST. LOUIS MO"],"commodity":"CANNED SOUP"},
      },
      {
        load_id: "A-11", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 12",
          "PO 31051 | Pickup 09/24/2026 07:00 CT | Shipper A Plant, Rockford IL",
          "Deliver Granite Peak Outfitters DC, Minneapolis MN | appt 15:00 CT",
          "53' Dry Van | Weight 40800 | Unit LB | Dry pasta",
        ],
        agent: {"reference":"PO-31051","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-24","pickup_appt":"07:00","delivery_facility":"Granite Peak Outfitters DC, Minneapolis MN","delivery_appt":"15:00","equipment":"53' Dry Van","weight_lbs":40800,"stops":["Rockford IL","Minneapolis MN"],"commodity":"Dry pasta"},
        rep: {"reference":"PO-31051","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/24/2026","pickup_appt":"0700","delivery_facility":"GRANITE PEAK OUTFITTERS DC, MINNEAPOLIS MN","delivery_appt":"1500","equipment":"53' DRY VAN","weight_lbs":40800,"stops":["ROCKFORD IL","MINNEAPOLIS MN"],"commodity":"DRY PASTA"},
      },
      {
        load_id: "A-12", shipper: "A", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 13",
          "PO 31052 | Pickup 09/25/2026 09:30 CT | Shipper A Plant, Rockford IL",
          "Deliver Fairmont Grocers DC, Des Moines IA | appt 16:00 CT",
          "53' Dry Van | Weight 38150 | Unit LB | Canned vegetables",
        ],
        agent: {"reference":"PO-31052","pickup_facility":"Shipper A Plant, Rockford IL","pickup_date":"2026-09-25","pickup_appt":"09:30","delivery_facility":"Fairmont Grocers DC, Des Moines IA","delivery_appt":"16:00","equipment":"53' Dry Van","weight_lbs":38150,"stops":["Rockford IL","Des Moines IA"],"commodity":"Canned vegetables"},
        rep: {"reference":"PO-31052 ","pickup_facility":"SHIPPER A PLANT, ROCKFORD IL","pickup_date":"09/25/2026","pickup_appt":"0930","delivery_facility":"FAIRMONT GROCERS DC, DES MOINES IA","delivery_appt":"1600","equipment":"53' DRY VAN","weight_lbs":38150,"stops":["ROCKFORD IL","DES MOINES IA"],"commodity":"CANNED VEGETABLES"},
      },
      {
        load_id: "B-01", shipper: "B", source_format: "Email",
        source: [
          "Subject: New load for 9/14",
          "Body: Please pick up 9/14 at 08:00 CT from Shipper B Warehouse, Memphis TN. PO 55101.",
          "Deliver to Kestrel Home DC, Nashville TN, appt 14:00 CT.",
          "53' Dry Van, 28,400 lb, Paper plates.",
        ],
        agent: {"reference":"PO-55101","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-14","pickup_appt":"08:00","delivery_facility":"Kestrel Home DC, Nashville TN","delivery_appt":"14:00","equipment":"53' Dry Van","weight_lbs":28400,"stops":["Memphis TN","Nashville TN"],"commodity":"Paper plates"},
        rep: {"reference":"PO-55101","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/14/2026","pickup_appt":"0800","delivery_facility":"KESTREL HOME DC, NASHVILLE TN","delivery_appt":"1400","equipment":"53' DRY VAN","weight_lbs":28400,"stops":["MEMPHIS TN","NASHVILLE TN"],"commodity":"PAPER PLATES"},
      },
      {
        load_id: "B-02", shipper: "B", source_format: "Email",
        source: [
          "Subject: New load for 9/14",
          "Body: Please pick up 9/14 at 07:00 CT from Shipper B Warehouse, Memphis TN. PO 55102.",
          "Deliver to Lone Oak Retail DC, Dallas TX, window 06:00-12:00 CT.",
          "53' Dry Van, 31,200 lb, Paper cups.",
        ],
        agent: {"reference":"PO-55102","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-14","pickup_appt":"07:00","delivery_facility":"Lone Oak Retail DC, Dallas TX","delivery_appt":"06:00-12:00","equipment":"53' Dry Van","weight_lbs":31200,"stops":["Memphis TN","Dallas TX"],"commodity":"Paper cups"},
        rep: {"reference":"PO-55102","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/14/2026","pickup_appt":"0700","delivery_facility":"LONE OAK RETAIL DC, DALLAS TX","delivery_appt":"0600-1200","equipment":"53' DRY VAN","weight_lbs":31200,"stops":["MEMPHIS TN","DALLAS TX"],"commodity":"PAPER CUPS"},
      },
      {
        load_id: "B-03", shipper: "B", source_format: "Email",
        source: [
          "Subject: New load for 9/15",
          "Body: Please pick up 9/15 at 09:00 CT from Shipper B Warehouse, Memphis TN. PO 55103.",
          "Deliver to Riverbend Supply, St. Louis MO, appt 15:30 CT.",
          "53' Dry Van, 26,750 lb, Paper plates.",
        ],
        agent: {"reference":"PO-55103","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-15","pickup_appt":"09:00","delivery_facility":"Riverbend Supply, St. Louis MO","delivery_appt":"15:30","equipment":"53' Dry Van","weight_lbs":26750,"stops":["Memphis TN","St. Louis MO"],"commodity":"Paper plates"},
        rep: {"reference":"PO-55103","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/15/2026","pickup_appt":"0900","delivery_facility":"RIVERBEND SUPPLY, ST. LOUIS MO","delivery_appt":"1530","equipment":"53' DRY VAN","weight_lbs":26750,"stops":["MEMPHIS TN","ST. LOUIS MO"],"commodity":"PAPER PLATES"},
      },
      {
        load_id: "B-04", shipper: "B", source_format: "Email",
        source: [
          "Subject: Tender PO 55104",
          "Body: Please pick up 9/16 at 06:00 CT from Shipper B Warehouse, Memphis TN.",
          "Deliver to Bluestem Market DC, Kansas City MO, window 07:00-13:00 CT.",
          "53' Dry Van, 30,500 lb, Napkins.",
        ],
        agent: {"reference":"","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-16","pickup_appt":"06:00","delivery_facility":"Bluestem Market DC, Kansas City MO","delivery_appt":"07:00-13:00","equipment":"53' Dry Van","weight_lbs":30500,"stops":["Memphis TN","Kansas City MO"],"commodity":"Napkins"},
        rep: {"reference":"PO-55104 ","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/16/2026","pickup_appt":"0600","delivery_facility":"BLUESTEM MARKET DC, KANSAS CITY MO","delivery_appt":"0700-1300","equipment":"53' DRY VAN","weight_lbs":30500,"stops":["MEMPHIS TN","KANSAS CITY MO"],"commodity":"NAPKINS"},
      },
      {
        load_id: "B-05", shipper: "B", source_format: "Email",
        source: [
          "Subject: New load for 9/17",
          "Body: Please pick up 9/17 at 10:00 CT from Shipper B Warehouse, Memphis TN. PO 55105.",
          "Deliver to Kestrel Home DC, Nashville TN, appt 16:00 CT.",
          "53' Dry Van, 24,900 lb, Paper cups.",
        ],
        agent: {"reference":"PO-55105","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-17","pickup_appt":"10:00","delivery_facility":"Kestrel Home DC, Nashville TN","delivery_appt":"16:00","equipment":"53' Dry Van","weight_lbs":24900,"stops":["Memphis TN","Nashville TN"],"commodity":"Paper cups"},
        rep: {"reference":"PO-55105","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/17/2026","pickup_appt":"1000","delivery_facility":"KESTREL HOME DC, NASHVILLE TN","delivery_appt":"1600","equipment":"53' DRY VAN","weight_lbs":24900,"stops":["MEMPHIS TN","NASHVILLE TN"],"commodity":"PAPER CUPS"},
      },
      {
        load_id: "B-06", shipper: "B", source_format: "Email",
        source: [
          "Subject: New load for 9/18",
          "Body: Please pick up 9/18 at 08:30 CT from Shipper B Warehouse, Memphis TN. PO 55106.",
          "Deliver to Lone Oak Retail DC, Dallas TX, appt 09:00 CT.",
          "53' Dry Van, 29,800 lb, Napkins.",
        ],
        agent: {"reference":"PO-55106","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-18","pickup_appt":"08:30","delivery_facility":"Lone Oak Retail DC, Dallas TX","delivery_appt":"09:00","equipment":"53' Dry Van","weight_lbs":29800,"stops":["Memphis TN","Dallas TX"],"commodity":"Napkins"},
        rep: {"reference":"PO-55106","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/18/2026","pickup_appt":"0830","delivery_facility":"LONE OAK RETAIL DC, DALLAS TX","delivery_appt":"0900","equipment":"53' DRY VAN","weight_lbs":29800,"stops":["MEMPHIS TN","DALLAS TX"],"commodity":"NAPKINS"},
      },
      {
        load_id: "B-07", shipper: "B", source_format: "Email",
        source: [
          "Subject: New load for 9/21",
          "Body: Please pick up 9/21 at 07:00 CT from Shipper B Warehouse, Memphis TN. PO 55107.",
          "Deliver to Fairmont Grocers DC, Des Moines IA, window 08:00-12:00 CT.",
          "53' Dry Van, 27,650 lb, Paper plates.",
        ],
        agent: {"reference":"PO-55107","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-21","pickup_appt":"07:00","delivery_facility":"Fairmont Grocers DC, Des Moines IA","delivery_appt":"08:00-12:00","equipment":"53' Dry Van","weight_lbs":27650,"stops":["Memphis TN","Des Moines IA"],"commodity":"Paper plates"},
        rep: {"reference":"PO-55107","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/21/2026","pickup_appt":"0700","delivery_facility":"FAIRMONT GROCERS DC, DES MOINES IA","delivery_appt":"0800-1200","equipment":"53' DRY VAN","weight_lbs":27650,"stops":["MEMPHIS TN","DES MOINES IA"],"commodity":"PAPER PLATES"},
      },
      {
        load_id: "B-08", shipper: "B", source_format: "Email",
        source: [
          "Subject: New load for 9/21",
          "Body: Please pick up 9/21 at 06:30 CT from Shipper B Warehouse, Memphis TN. PO 55108.",
          "Deliver to Riverbend Supply, St. Louis MO, appt 13:00 CT.",
          "53' Dry Van, 32,100 lb, Paper cups.",
        ],
        agent: {"reference":"PO-55108","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-21","pickup_appt":"06:30","delivery_facility":"Riverbend Supply, St. Louis MO","delivery_appt":"13:00","equipment":"53' Dry Van","weight_lbs":32100,"stops":["Memphis TN","St. Louis MO"],"commodity":"Paper cups"},
        rep: {"reference":"PO-55108 ","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/21/2026","pickup_appt":"0630","delivery_facility":"RIVERBEND SUPPLY, ST. LOUIS MO","delivery_appt":"1300","equipment":"53' DRY VAN","weight_lbs":32100,"stops":["MEMPHIS TN","ST. LOUIS MO"],"commodity":"PAPER CUPS"},
      },
      {
        load_id: "B-09", shipper: "B", source_format: "Email",
        source: [
          "Subject: Tender PO 55109",
          "Body: Please pick up 9/22 at 09:00 CT from Shipper B Warehouse, Memphis TN.",
          "Deliver to Kestrel Home DC, Nashville TN, window 06:00-10:00 CT.",
          "53' Dry Van, 25,300 lb, Napkins.",
        ],
        agent: {"reference":"","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-22","pickup_appt":"09:00","delivery_facility":"Kestrel Home DC, Nashville TN","delivery_appt":"06:00-10:00","equipment":"53' Dry Van","weight_lbs":25300,"stops":["Memphis TN","Nashville TN"],"commodity":"Napkins"},
        rep: {"reference":"PO-55109","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/22/2026","pickup_appt":"0900","delivery_facility":"KESTREL HOME DC, NASHVILLE TN","delivery_appt":"0600-1000","equipment":"53' DRY VAN","weight_lbs":25300,"stops":["MEMPHIS TN","NASHVILLE TN"],"commodity":"NAPKINS"},
      },
      {
        load_id: "B-10", shipper: "B", source_format: "Email",
        source: [
          "Subject: New load for 9/23",
          "Body: Please pick up 9/23 at 07:30 CT from Shipper B Warehouse, Memphis TN. PO 55110.",
          "Deliver to Lone Oak Retail DC, Dallas TX, appt 14:30 CT.",
          "53' Dry Van, 30,900 lb, Paper plates.",
        ],
        agent: {"reference":"PO-55110","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-23","pickup_appt":"07:30","delivery_facility":"Lone Oak Retail DC, Dallas TX","delivery_appt":"14:30","equipment":"53' Dry Van","weight_lbs":30900,"stops":["Memphis TN","Dallas TX"],"commodity":"Paper plates"},
        rep: {"reference":"PO-55110","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/23/2026","pickup_appt":"0730","delivery_facility":"LONE OAK RETAIL DC, DALLAS TX","delivery_appt":"1430","equipment":"53' DRY VAN","weight_lbs":30900,"stops":["MEMPHIS TN","DALLAS TX"],"commodity":"PAPER PLATES"},
      },
      {
        load_id: "B-11", shipper: "B", source_format: "Email",
        source: [
          "Subject: New load for 9/24",
          "Body: Please pick up 9/24 at 08:00 CT from Shipper B Warehouse, Memphis TN. PO 55111.",
          "Deliver to Bluestem Market DC, Kansas City MO, appt 12:00 CT.",
          "53' Dry Van, 28,800 lb, Paper cups.",
        ],
        agent: {"reference":"PO-55111","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-24","pickup_appt":"08:00","delivery_facility":"Bluestem Market DC, Kansas City MO","delivery_appt":"12:00","equipment":"53' Dry Van","weight_lbs":28800,"stops":["Memphis TN","Kansas City MO"],"commodity":"Paper cups"},
        rep: {"reference":"PO-55111","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/24/2026","pickup_appt":"0800","delivery_facility":"BLUESTEM MARKET DC, KANSAS CITY MO","delivery_appt":"1200","equipment":"53' DRY VAN","weight_lbs":28800,"stops":["MEMPHIS TN","KANSAS CITY MO"],"commodity":"PAPER CUPS"},
      },
      {
        load_id: "B-12", shipper: "B", source_format: "Email",
        source: [
          "Subject: New load for 9/25",
          "Body: Please pick up 9/25 at 10:30 CT from Shipper B Warehouse, Memphis TN. PO 55112.",
          "Deliver to Riverbend Supply, St. Louis MO, window 07:00-11:00 CT.",
          "53' Dry Van, 26,100 lb, Napkins.",
        ],
        agent: {"reference":"PO-55112","pickup_facility":"Shipper B Warehouse, Memphis TN","pickup_date":"2026-09-25","pickup_appt":"10:30","delivery_facility":"Riverbend Supply, St. Louis MO","delivery_appt":"07:00-11:00","equipment":"53' Dry Van","weight_lbs":26100,"stops":["Memphis TN","St. Louis MO"],"commodity":"Napkins"},
        rep: {"reference":"PO-55112 ","pickup_facility":"SHIPPER B WAREHOUSE, MEMPHIS TN","pickup_date":"09/25/2026","pickup_appt":"1030","delivery_facility":"RIVERBEND SUPPLY, ST. LOUIS MO","delivery_appt":"0700-1100","equipment":"53' DRY VAN","weight_lbs":26100,"stops":["MEMPHIS TN","ST. LOUIS MO"],"commodity":"NAPKINS"},
      },
      {
        load_id: "C-01", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48211 | Ship date 09/14/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 06:00 CT",
          "Consignee: Harlow Foods DC 14, Elwood IL, appt 12:00 CT",
          "53' Dry Van, 43,500 lb, Bagged flour",
        ],
        agent: {"reference":"PO-48211","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-14","pickup_appt":"06:00","delivery_facility":"Harlow Foods DC 14, Elwood IL","delivery_appt":"12:00","equipment":"53' Dry Van","weight_lbs":43500,"stops":["Peoria IL","Elwood IL"],"commodity":"Bagged flour"},
        rep: {"reference":"PO-48211","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/14/2026","pickup_appt":"0600","delivery_facility":"HARLOW FOODS DC 14, ELWOOD IL","delivery_appt":"1200","equipment":"53' DRY VAN","weight_lbs":43500,"stops":["PEORIA IL","ELWOOD IL"],"commodity":"BAGGED FLOUR"},
      },
      {
        load_id: "C-02", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48212 | Ship date 09/14/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 07:00 CT",
          "Consignee: Riverbend Supply, St. Louis MO, window 06:00-11:00 CT",
          "53' Dry Van, 42,100 lb, Baking mix",
        ],
        agent: {"reference":"PO-48212","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-14","pickup_appt":"07:00","delivery_facility":"Riverbend Supply, St. Louis MO","delivery_appt":"06:00-11:00","equipment":"53' Dry Van","weight_lbs":42100,"stops":["Peoria IL","St. Louis MO"],"commodity":"Baking mix"},
        rep: {"reference":"PO-48212","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/14/2026","pickup_appt":"0700","delivery_facility":"RIVERBEND SUPPLY, ST. LOUIS MO","delivery_appt":"0600-1100","equipment":"53' DRY VAN","weight_lbs":42100,"stops":["PEORIA IL","ST. LOUIS MO"],"commodity":"BAKING MIX"},
      },
      {
        load_id: "C-03", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48213 | Ship date 09/15/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 08:00 CT",
          "Consignee: Fairmont Grocers DC, Des Moines IA, window 08:00-14:00 CT",
          "53' Dry Van, 44,000 lb, Bagged flour",
        ],
        agent: {"reference":"PO-48213","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-15","pickup_appt":"08:00","delivery_facility":"Fairmont Grocers DC, Des Moines IA","delivery_appt":"08:00","equipment":"53' Dry Van","weight_lbs":44000,"stops":["Peoria IL","Des Moines IA"],"commodity":"Bagged flour"},
        rep: {"reference":"PO-48213","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/15/2026","pickup_appt":"0800","delivery_facility":"FAIRMONT GROCERS DC, DES MOINES IA","delivery_appt":"0800-1400","equipment":"53' DRY VAN","weight_lbs":44000,"stops":["PEORIA IL","DES MOINES IA"],"commodity":"BAGGED FLOUR"},
      },
      {
        load_id: "C-04", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48214 | Ship date 09/16/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 06:30 CT",
          "Consignee: Northline Hardware DC, Madison WI, appt 13:00 CT",
          "53' Dry Van, 39,800 lb, Baking mix",
        ],
        agent: {"reference":"PO-48214","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-16","pickup_appt":"06:30","delivery_facility":"Northline Hardware DC, Madison WI","delivery_appt":"13:00","equipment":"53' Dry Van","weight_lbs":39800,"stops":["Peoria IL","Madison WI"],"commodity":"Baking mix"},
        rep: {"reference":"PO-48214 ","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/16/2026","pickup_appt":"0630","delivery_facility":"NORTHLINE HARDWARE DC, MADISON WI","delivery_appt":"1300","equipment":"53' DRY VAN","weight_lbs":39800,"stops":["PEORIA IL","MADISON WI"],"commodity":"BAKING MIX"},
      },
      {
        load_id: "C-05", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48215 | Ship date 09/17/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 07:30 CT",
          "Consignee: Bluestem Market DC, Kansas City MO, appt 15:00 CT",
          "53' Dry Van, 41,700 lb, Bagged flour",
        ],
        agent: {"reference":"PO-48215","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-17","pickup_appt":"07:30","delivery_facility":"Bluestem Market DC, Kansas City MO","delivery_appt":"15:00","equipment":"53' Dry Van","weight_lbs":41700,"stops":["Peoria IL","Kansas City MO"],"commodity":"Bagged flour"},
        rep: {"reference":"PO-48215","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/18/2026","pickup_appt":"0730","delivery_facility":"BLUESTEM MARKET DC, KANSAS CITY MO","delivery_appt":"1500","equipment":"53' DRY VAN","weight_lbs":41700,"stops":["PEORIA IL","KANSAS CITY MO"],"commodity":"BAGGED FLOUR"},
        disputed: [{"field":"pickup_date","note":"Tender says 09/17/2026; the agent matches it and the rep keyed 09/18/2026."}],
      },
      {
        load_id: "C-06", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48216 | Ship date 09/18/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 09:00 CT",
          "Consignee: Harlow Foods DC 14, Elwood IL, window 07:00-12:00 CT",
          "53' Dry Van, 43,200 lb, Cornmeal",
        ],
        agent: {"reference":"PO-48216","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-18","pickup_appt":"09:00","delivery_facility":"Harlow Foods DC 14, Elwood IL","delivery_appt":"07:00-12:00","equipment":"53' Dry Van","weight_lbs":43200,"stops":["Peoria IL","Elwood IL"],"commodity":"Cornmeal"},
        rep: {"reference":"PO-48216","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/18/2026","pickup_appt":"0900","delivery_facility":"HARLOW FOODS DC 14, ELWOOD IL","delivery_appt":"0700-1200","equipment":"53' DRY VAN","weight_lbs":43200,"stops":["PEORIA IL","ELWOOD IL"],"commodity":"CORNMEAL"},
      },
      {
        load_id: "C-07", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48217 | Ship date 09/21/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 06:00 CT",
          "Consignee: Prairie Pantry DC, Omaha NE, appt 14:00 CT",
          "53' Dry Van, 40,600 lb, Bagged flour",
        ],
        agent: {"reference":"PO-48217","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-21","pickup_appt":"06:00","delivery_facility":"Prairie Pantry DC, Omaha NE","delivery_appt":"14:00","equipment":"53' Dry Van","weight_lbs":40600,"stops":["Peoria IL","Omaha NE"],"commodity":"Bagged flour"},
        rep: {"reference":"PO-48217","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/21/2026","pickup_appt":"0600","delivery_facility":"PRAIRIE PANTRY DC, OMAHA NE","delivery_appt":"1400","equipment":"53' DRY VAN","weight_lbs":40600,"stops":["PEORIA IL","OMAHA NE"],"commodity":"BAGGED FLOUR"},
      },
      {
        load_id: "C-08", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48218 | Ship date 09/21/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 08:00 CT",
          "Consignee: Riverbend Supply, St. Louis MO, appt 10:00 CT",
          "53' Dry Van, 42,900 lb, Baking mix",
        ],
        agent: {"reference":"PO-48218","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-21","pickup_appt":"08:00","delivery_facility":"Riverbend Supply, St. Louis MO","delivery_appt":"10:00","equipment":"53' Dry Van","weight_lbs":42900,"stops":["Peoria IL","St. Louis MO"],"commodity":"Baking mix"},
        rep: {"reference":"PO-48218 ","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/21/2026","pickup_appt":"0800","delivery_facility":"RIVERBEND SUPPLY, ST. LOUIS MO","delivery_appt":"1000","equipment":"53' DRY VAN","weight_lbs":42900,"stops":["PEORIA IL","ST. LOUIS MO"],"commodity":"BAKING MIX"},
      },
      {
        load_id: "C-09", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48219 | Ship date 09/22/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 07:00 CT",
          "Consignee: Northline Hardware DC, Madison WI, window 06:00-10:00 CT",
          "53' Dry Van, 38,700 lb, Cornmeal",
        ],
        agent: {"reference":"PO-48219","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-22","pickup_appt":"07:00","delivery_facility":"Northline Hardware DC, Madison WI","delivery_appt":"06:00-10:00","equipment":"53' Dry Van","weight_lbs":38700,"stops":["Peoria IL","Madison WI"],"commodity":"Cornmeal"},
        rep: {"reference":"PO-48219","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/22/2026","pickup_appt":"0700","delivery_facility":"NORTHLINE HARDWARE DC, MADISON WI","delivery_appt":"0600-1000","equipment":"53' DRY VAN","weight_lbs":38700,"stops":["PEORIA IL","MADISON WI"],"commodity":"CORNMEAL"},
      },
      {
        load_id: "C-10", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48220 | Ship date 09/23/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 10:00 CT",
          "Consignee: Fairmont Grocers DC, Des Moines IA, appt 16:00 CT",
          "53' Dry Van, 43,800 lb, Bagged flour",
        ],
        agent: {"reference":"PO-48220","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-23","pickup_appt":"10:00","delivery_facility":"Fairmont Grocers DC, Des Moines IA","delivery_appt":"16:00","equipment":"53' Dry Van","weight_lbs":43800,"stops":["Peoria IL","Des Moines IA"],"commodity":"Bagged flour"},
        rep: {"reference":"PO-48220","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/23/2026","pickup_appt":"1000","delivery_facility":"FAIRMONT GROCERS DC, DES MOINES IA","delivery_appt":"1600","equipment":"53' DRY VAN","weight_lbs":43800,"stops":["PEORIA IL","DES MOINES IA"],"commodity":"BAGGED FLOUR"},
      },
      {
        load_id: "C-11", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48221 | Ship date 09/24/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 06:30 CT",
          "Consignee: Harlow Foods DC 14, Elwood IL, appt 11:30 CT",
          "53' Dry Van, 41,300 lb, Baking mix",
        ],
        agent: {"reference":"PO-48221","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-24","pickup_appt":"06:30","delivery_facility":"Harlow Foods DC 14, Elwood IL","delivery_appt":"11:30","equipment":"53' Dry Van","weight_lbs":41300,"stops":["Peoria IL","Elwood IL"],"commodity":"Baking mix"},
        rep: {"reference":"PO-48221","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/24/2026","pickup_appt":"0630","delivery_facility":"HARLOW FOODS DC 14, ELWOOD IL","delivery_appt":"1130","equipment":"53' DRY VAN","weight_lbs":41300,"stops":["PEORIA IL","ELWOOD IL"],"commodity":"BAKING MIX"},
      },
      {
        load_id: "C-12", shipper: "C", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 48222 | Ship date 09/25/2026",
          "Pickup: Shipper C Mill, Peoria IL, appt 08:30 CT",
          "Consignee: Bluestem Market DC, Kansas City MO, window 08:00-13:00 CT",
          "53' Dry Van, 42,450 lb, Cornmeal",
        ],
        agent: {"reference":"PO-48222","pickup_facility":"Shipper C Mill, Peoria IL","pickup_date":"2026-09-25","pickup_appt":"08:30","delivery_facility":"Bluestem Market DC, Kansas City MO","delivery_appt":"08:00-13:00","equipment":"53' Dry Van","weight_lbs":42450,"stops":["Peoria IL","Kansas City MO"],"commodity":"Cornmeal"},
        rep: {"reference":"PO-48222 ","pickup_facility":"SHIPPER C MILL, PEORIA IL","pickup_date":"09/25/2026","pickup_appt":"0830","delivery_facility":"BLUESTEM MARKET DC, KANSAS CITY MO","delivery_appt":"0800-1300","equipment":"53' DRY VAN","weight_lbs":42450,"stops":["PEORIA IL","KANSAS CITY MO"],"commodity":"CORNMEAL"},
      },
      {
        load_id: "D-01", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70301 | Ship date 09/14/2026",
          "Pickup: Shipper D Plant, Columbus OH, appt 10:00 local",
          "Consignee: Harlow Foods DC 14, Elwood IL, appt 06:00 CT",
          "53' Reefer, 39,200 lb, Yogurt",
        ],
        agent: {"reference":"PO-70301","pickup_facility":"Shipper D Plant, Columbus OH","pickup_date":"2026-09-14","pickup_appt":"10:00","delivery_facility":"Harlow Foods DC 14, Elwood IL","delivery_appt":"06:00","equipment":"53' Reefer","weight_lbs":39200,"stops":["Columbus OH","Elwood IL"],"commodity":"Yogurt"},
        rep: {"reference":"PO-70301","pickup_facility":"SHIPPER D PLANT, COLUMBUS OH","pickup_date":"09/14/2026","pickup_appt":"0900","delivery_facility":"HARLOW FOODS DC 14, ELWOOD IL","delivery_appt":"0600","equipment":"53' REEFER","weight_lbs":39200,"stops":["COLUMBUS OH","ELWOOD IL"],"commodity":"YOGURT"},
      },
      {
        load_id: "D-02", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70302 | Ship date 09/14/2026",
          "Pickup: Shipper D Plant, Springfield IL, appt 07:00 local",
          "Consignee: Harlow DC 4, window 05:00-09:00 CT",
          "53' Reefer, 40,100 lb, Cheese",
        ],
        agent: {"reference":"PO-70302","pickup_facility":"Shipper D Plant, Springfield IL","pickup_date":"2026-09-14","pickup_appt":"07:00","delivery_facility":"Harlow Foods DC 4, Joliet IL","delivery_appt":"05:00-09:00","equipment":"53' Reefer","weight_lbs":40100,"stops":["Springfield IL","Joliet IL"],"commodity":"Cheese"},
        rep: {"reference":"PO-70302","pickup_facility":"SHIPPER D PLANT, SPRINGFIELD IL","pickup_date":"09/14/2026","pickup_appt":"0700","delivery_facility":"HARLOW FOODS DC 4, JOLIET IL","delivery_appt":"0500-0900","equipment":"53' REEFER","weight_lbs":40100,"stops":["SPRINGFIELD IL","JOLIET IL"],"commodity":"CHEESE"},
      },
      {
        load_id: "D-03", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70303 | Ship date 09/15/2026",
          "Pickup: Shipper D Plant, Columbus OH, appt 11:00 local",
          "Consignee: Cedar Hollow Foods DC, Memphis TN, appt 07:00 CT",
          "53' Reefer, 36,500 lb, Milk",
        ],
        agent: {"reference":"PO-70303","pickup_facility":"Shipper D Plant, Columbus OH","pickup_date":"2026-09-15","pickup_appt":"11:00","delivery_facility":"Cedar Hollow Foods DC, Memphis TN","delivery_appt":"07:00","equipment":"53' Reefer","weight_lbs":36500,"stops":["Columbus OH","Memphis TN"],"commodity":"Milk"},
        rep: {"reference":"PO-70303","pickup_facility":"SHIPPER D PLANT, COLUMBUS OH","pickup_date":"09/15/2026","pickup_appt":"1000","delivery_facility":"CEDAR HOLLOW FOODS DC, MEMPHIS TN","delivery_appt":"0700","equipment":"53' REEFER","weight_lbs":36500,"stops":["COLUMBUS OH","MEMPHIS TN"],"commodity":"MILK"},
      },
      {
        load_id: "D-04", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70304 | Ship date 09/16/2026",
          "Pickup: Shipper D Plant, Springfield IL, appt 06:00 local",
          "Consignee: Harlow DC 4, window 06:00-10:00 CT",
          "53' Reefer, 38,800 lb, Yogurt",
        ],
        agent: {"reference":"PO-70304","pickup_facility":"Shipper D Plant, Springfield IL","pickup_date":"2026-09-16","pickup_appt":"06:00","delivery_facility":"Harlow Foods DC 4 Annex, Joliet IL","delivery_appt":"06:00-10:00","equipment":"53' Reefer","weight_lbs":38800,"stops":["Springfield IL","Joliet IL"],"commodity":"Yogurt"},
        rep: {"reference":"PO-70304 ","pickup_facility":"SHIPPER D PLANT, SPRINGFIELD IL","pickup_date":"09/16/2026","pickup_appt":"0600","delivery_facility":"HARLOW FOODS DC 4, JOLIET IL","delivery_appt":"0600-1000","equipment":"53' REEFER","weight_lbs":38800,"stops":["SPRINGFIELD IL","JOLIET IL"],"commodity":"YOGURT"},
      },
      {
        load_id: "D-05", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70305 | Ship date 09/17/2026",
          "Pickup: Shipper D Plant, Springfield IL, appt 08:00 local",
          "Consignee: Kestrel Home DC, Nashville TN, appt 14:00 CT",
          "53' Reefer, 37,400 lb, Cheese",
        ],
        agent: {"reference":"PO-70305","pickup_facility":"Shipper D Plant, Springfield IL","pickup_date":"2026-09-17","pickup_appt":"08:00","delivery_facility":"Kestrel Home DC, Nashville TN","delivery_appt":"14:00","equipment":"53' Reefer","weight_lbs":37400,"stops":["Springfield IL","Nashville TN"],"commodity":"Cheese"},
        rep: {"reference":"PO-70305","pickup_facility":"SHIPPER D PLANT, SPRINGFIELD IL","pickup_date":"09/17/2026","pickup_appt":"0800","delivery_facility":"KESTREL HOME DC, NASHVILLE TN","delivery_appt":"1400","equipment":"53' REEFER","weight_lbs":37400,"stops":["SPRINGFIELD IL","NASHVILLE TN"],"commodity":"CHEESE"},
      },
      {
        load_id: "D-06", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70306 | Ship date 09/18/2026",
          "Pickup: Shipper D Plant, Columbus OH, appt 09:00 local",
          "Consignee: Harlow Foods DC 14, Elwood IL, appt 05:00 CT",
          "53' Reefer, 41,000 lb, Milk",
        ],
        agent: {"reference":"PO-70306","pickup_facility":"Shipper D Plant, Columbus OH","pickup_date":"2026-09-18","pickup_appt":"09:00","delivery_facility":"Harlow Foods DC 14, Elwood IL","delivery_appt":"05:00","equipment":"53' Reefer","weight_lbs":41000,"stops":["Columbus OH","Elwood IL"],"commodity":"Milk"},
        rep: {"reference":"PO-70306","pickup_facility":"SHIPPER D PLANT, COLUMBUS OH","pickup_date":"09/18/2026","pickup_appt":"0800","delivery_facility":"HARLOW FOODS DC 14, ELWOOD IL","delivery_appt":"0500","equipment":"53' REEFER","weight_lbs":41000,"stops":["COLUMBUS OH","ELWOOD IL"],"commodity":"MILK"},
      },
      {
        load_id: "D-07", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70307 | Ship date 09/21/2026",
          "Pickup: Shipper D Plant, Springfield IL, appt 07:30 local",
          "Consignee: Harlow DC 4, window 07:00-11:00 CT",
          "53' Reefer, 39,600 lb, Butter",
        ],
        agent: {"reference":"PO-70307","pickup_facility":"Shipper D Plant, Springfield IL","pickup_date":"2026-09-21","pickup_appt":"07:30","delivery_facility":"Harlow Foods DC 4, Joliet IL","delivery_appt":"07:00-11:00","equipment":"53' Reefer","weight_lbs":39600,"stops":["Springfield IL","Joliet IL"],"commodity":"Butter"},
        rep: {"reference":"PO-70307","pickup_facility":"SHIPPER D PLANT, SPRINGFIELD IL","pickup_date":"09/21/2026","pickup_appt":"0730","delivery_facility":"HARLOW FOODS DC 4, JOLIET IL","delivery_appt":"0700-1100","equipment":"53' REEFER","weight_lbs":39600,"stops":["SPRINGFIELD IL","JOLIET IL"],"commodity":"BUTTER"},
      },
      {
        load_id: "D-08", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70308 | Ship date 09/21/2026",
          "Pickup: Shipper D Plant, Columbus OH, appt 12:00 local",
          "Consignee: Riverbend Supply, St. Louis MO, appt 08:00 CT",
          "53' Reefer, 35,900 lb, Yogurt",
        ],
        agent: {"reference":"PO-70308","pickup_facility":"Shipper D Plant, Columbus OH","pickup_date":"2026-09-21","pickup_appt":"12:00","delivery_facility":"Riverbend Supply, St. Louis MO","delivery_appt":"08:00","equipment":"53' Reefer","weight_lbs":35900,"stops":["Columbus OH","St. Louis MO"],"commodity":"Yogurt"},
        rep: {"reference":"PO-70308 ","pickup_facility":"SHIPPER D PLANT, COLUMBUS OH","pickup_date":"09/21/2026","pickup_appt":"1100","delivery_facility":"RIVERBEND SUPPLY, ST. LOUIS MO","delivery_appt":"0800","equipment":"53' REEFER","weight_lbs":35900,"stops":["COLUMBUS OH","ST. LOUIS MO"],"commodity":"YOGURT"},
      },
      {
        load_id: "D-09", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70309 | Ship date 09/22/2026",
          "Pickup: Shipper D Plant, Springfield IL, appt 06:00 local",
          "Consignee: Prairie Pantry DC, Omaha NE, appt 13:00 CT",
          "53' Reefer, 40,300 lb, Cheese",
        ],
        agent: {"reference":"PO-70309","pickup_facility":"Shipper D Plant, Springfield IL","pickup_date":"2026-09-22","pickup_appt":"06:00","delivery_facility":"Prairie Pantry DC, Omaha NE","delivery_appt":"13:00","equipment":"53' Reefer","weight_lbs":40300,"stops":["Springfield IL","Omaha NE"],"commodity":"Cheese"},
        rep: {"reference":"PO-70309","pickup_facility":"SHIPPER D PLANT, SPRINGFIELD IL","pickup_date":"09/22/2026","pickup_appt":"0600","delivery_facility":"PRAIRIE PANTRY DC, OMAHA NE","delivery_appt":"1300","equipment":"53' REEFER","weight_lbs":40300,"stops":["SPRINGFIELD IL","OMAHA NE"],"commodity":"CHEESE"},
      },
      {
        load_id: "D-10", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70310 | Ship date 09/23/2026",
          "Pickup: Shipper D Plant, Springfield IL, appt 08:00 local",
          "Consignee: Harlow DC 4, window 05:00-09:00 CT",
          "53' Reefer, 38,200 lb, Milk",
        ],
        agent: {"reference":"PO-70310","pickup_facility":"Shipper D Plant, Springfield IL","pickup_date":"2026-09-23","pickup_appt":"08:00","delivery_facility":"Harlow Foods DC 4 Annex, Joliet IL","delivery_appt":"05:00-09:00","equipment":"53' Reefer","weight_lbs":38200,"stops":["Springfield IL","Joliet IL"],"commodity":"Milk"},
        rep: {"reference":"PO-70310","pickup_facility":"SHIPPER D PLANT, SPRINGFIELD IL","pickup_date":"09/23/2026","pickup_appt":"0800","delivery_facility":"HARLOW FOODS DC 4, JOLIET IL","delivery_appt":"0500-0900","equipment":"53' REEFER","weight_lbs":38200,"stops":["SPRINGFIELD IL","JOLIET IL"],"commodity":"MILK"},
      },
      {
        load_id: "D-11", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70311 | Ship date 09/24/2026",
          "Pickup: Shipper D Plant, Columbus OH, appt 10:30 local",
          "Consignee: Cedar Hollow Foods DC, Memphis TN, appt 06:30 CT",
          "53' Reefer, 37,100 lb, Butter",
        ],
        agent: {"reference":"PO-70311","pickup_facility":"Shipper D Plant, Columbus OH","pickup_date":"2026-09-24","pickup_appt":"10:30","delivery_facility":"Cedar Hollow Foods DC, Memphis TN","delivery_appt":"06:30","equipment":"53' Reefer","weight_lbs":37100,"stops":["Columbus OH","Memphis TN"],"commodity":"Butter"},
        rep: {"reference":"PO-70311","pickup_facility":"SHIPPER D PLANT, COLUMBUS OH","pickup_date":"09/24/2026","pickup_appt":"0930","delivery_facility":"CEDAR HOLLOW FOODS DC, MEMPHIS TN","delivery_appt":"0630","equipment":"53' REEFER","weight_lbs":37100,"stops":["COLUMBUS OH","MEMPHIS TN"],"commodity":"BUTTER"},
      },
      {
        load_id: "D-12", shipper: "D", source_format: "PDF",
        source: [
          "Load tender, page 1 | Ref PO 70312 | Ship date 09/25/2026",
          "Pickup: Shipper D Plant, Springfield IL, appt 07:00 local",
          "Consignee: Harlow Foods DC 14, Elwood IL, appt 12:00 CT",
          "53' Reefer, 39,800 lb, Yogurt",
        ],
        agent: {"reference":"PO-70312","pickup_facility":"Shipper D Plant, Springfield IL","pickup_date":"2026-09-25","pickup_appt":"07:00","delivery_facility":"Harlow Foods DC 14, Elwood IL","delivery_appt":"12:00","equipment":"53' Reefer","weight_lbs":39800,"stops":["Springfield IL","Elwood IL"],"commodity":"Yogurt"},
        rep: {"reference":"PO-70312 ","pickup_facility":"SHIPPER D PLANT, SPRINGFIELD IL","pickup_date":"09/25/2026","pickup_appt":"0700","delivery_facility":"HARLOW FOODS DC 14, ELWOOD IL","delivery_appt":"1200","equipment":"53' REEFER","weight_lbs":39800,"stops":["SPRINGFIELD IL","ELWOOD IL"],"commodity":"YOGURT"},
      },
      {
        load_id: "E-01", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/14",
          "Body: Please pick up 9/14 at 07:00 CT from Shipper E Warehouse, Milwaukee WI. PO 61901.",
          "Deliver to Northline Hardware DC, Madison WI, appt 11:00 CT.",
          "53' Dry Van, 24,600 lb, Laundry detergent.",
        ],
        agent: {"reference":"PO-61901","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-14","pickup_appt":"07:00","delivery_facility":"Northline Hardware DC, Madison WI","delivery_appt":"11:00","equipment":"53' Dry Van","weight_lbs":24600,"stops":["Milwaukee WI","Madison WI"],"commodity":"Laundry detergent"},
        rep: {"reference":"PO-61901","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/14/2026","pickup_appt":"0700","delivery_facility":"NORTHLINE HARDWARE DC, MADISON WI","delivery_appt":"1100","equipment":"53' DRY VAN","weight_lbs":24600,"stops":["MILWAUKEE WI","MADISON WI"],"commodity":"LAUNDRY DETERGENT"},
      },
      {
        load_id: "E-02", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/14",
          "Body: Please pick up 9/14 at 06:00 CT from Shipper E Warehouse, Milwaukee WI. PO 61902.",
          "Deliver to Granite Peak Outfitters DC, Minneapolis MN, appt 15:00 CT. Stops in order: Madison WI, Eau Claire WI, then Minneapolis MN.",
          "53' Dry Van, 33,800 lb, Paper towels.",
        ],
        agent: {"reference":"PO-61902","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-14","pickup_appt":"06:00","delivery_facility":"Granite Peak Outfitters DC, Minneapolis MN","delivery_appt":"15:00","equipment":"53' Dry Van","weight_lbs":33800,"stops":["Milwaukee WI","Madison WI","Eau Claire WI","Minneapolis MN"],"commodity":"Paper towels"},
        rep: {"reference":"PO-61902","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/14/2026","pickup_appt":"0600","delivery_facility":"GRANITE PEAK OUTFITTERS DC, MINNEAPOLIS MN","delivery_appt":"1500","equipment":"53' DRY VAN","weight_lbs":33800,"stops":["MILWAUKEE WI","MADISON WI","EAU CLAIRE WI","MINNEAPOLIS MN"],"commodity":"PAPER TOWELS"},
      },
      {
        load_id: "E-03", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/15",
          "Body: Please pick up 9/15 at 08:00 CT from Shipper E Warehouse, Milwaukee WI. PO 61903.",
          "Deliver to Fairmont Grocers DC, Des Moines IA, appt 14:00 CT.",
          "53' Dry Van, 29,900 lb, Paper towels.",
        ],
        agent: {"reference":"PO-61903","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-15","pickup_appt":"08:00","delivery_facility":"Fairmont Grocers DC, Des Moines IA","delivery_appt":"14:00","equipment":"53' Dry Van","weight_lbs":29900,"stops":["Milwaukee WI","Des Moines IA"],"commodity":"Paper towels"},
        rep: {"reference":"PO-61903","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/15/2026","pickup_appt":"0800","delivery_facility":"FAIRMONT GROCERS DC, DES MOINES IA","delivery_appt":"1400","equipment":"53' DRY VAN","weight_lbs":29900,"stops":["MILWAUKEE WI","DES MOINES IA"],"commodity":"PAPER TWL"},
      },
      {
        load_id: "E-04", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/16",
          "Body: Please pick up 9/16 at 09:00 CT from Shipper E Warehouse, Milwaukee WI. PO 61904.",
          "Deliver to Northline Hardware DC, Madison WI, window 06:00-10:00 CT.",
          "53' Dry Van, 21,700 lb, Bottled water.",
        ],
        agent: {"reference":"PO-61904","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-16","pickup_appt":"09:00","delivery_facility":"Northline Hardware DC, Madison WI","delivery_appt":"06:00-10:00","equipment":"53' Dry Van","weight_lbs":21700,"stops":["Milwaukee WI","Madison WI"],"commodity":"Bottled water"},
        rep: {"reference":"PO-61904 ","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/16/2026","pickup_appt":"0900","delivery_facility":"NORTHLINE HARDWARE DC, MADISON WI","delivery_appt":"0600-1000","equipment":"53' DRY VAN","weight_lbs":21700,"stops":["MILWAUKEE WI","MADISON WI"],"commodity":"BOTTLED WATER"},
      },
      {
        load_id: "E-05", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/17",
          "Body: Please pick up 9/17 at 05:30 CT from Shipper E Warehouse, Milwaukee WI. PO 61905.",
          "Deliver to Granite Peak Outfitters DC, Minneapolis MN, appt 16:00 CT. Stops in order: Madison WI, La Crosse WI, then Minneapolis MN.",
          "53' Dry Van, 35,200 lb, Laundry detergent.",
        ],
        agent: {"reference":"PO-61905","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-17","pickup_appt":"05:30","delivery_facility":"Granite Peak Outfitters DC, Minneapolis MN","delivery_appt":"16:00","equipment":"53' Dry Van","weight_lbs":35200,"stops":["Milwaukee WI","La Crosse WI","Madison WI","Minneapolis MN"],"commodity":"Laundry detergent"},
        rep: {"reference":"PO-61905","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/17/2026","pickup_appt":"0530","delivery_facility":"GRANITE PEAK OUTFITTERS DC, MINNEAPOLIS MN","delivery_appt":"1600","equipment":"53' DRY VAN","weight_lbs":35200,"stops":["MILWAUKEE WI","MADISON WI","LA CROSSE WI","MINNEAPOLIS MN"],"commodity":"LAUNDRY DETERGENT"},
      },
      {
        load_id: "E-06", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/18",
          "Body: Please pick up 9/18 at 07:30 CT from Shipper E Warehouse, Milwaukee WI. PO 61906.",
          "Deliver to Prairie Pantry DC, Omaha NE, appt 13:30 CT.",
          "53' Dry Van, 30,400 lb, Bottled water.",
        ],
        agent: {"reference":"PO-61906","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-18","pickup_appt":"07:30","delivery_facility":"Prairie Pantry DC, Omaha NE","delivery_appt":"13:30","equipment":"53' Dry Van","weight_lbs":30400,"stops":["Milwaukee WI","Omaha NE"],"commodity":"Bottled water"},
        rep: {"reference":"PO-61906","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/18/2026","pickup_appt":"0730","delivery_facility":"PRAIRIE PANTRY DC, OMAHA NE","delivery_appt":"1330","equipment":"53' DRY VAN","weight_lbs":30400,"stops":["MILWAUKEE WI","OMAHA NE"],"commodity":"BOTTLED WATER"},
      },
      {
        load_id: "E-07", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/21",
          "Body: Please pick up 9/21 at 06:00 CT from Shipper E Warehouse, Milwaukee WI. PO 61907.",
          "Deliver to Fairmont Grocers DC, Des Moines IA, window 07:00-12:00 CT.",
          "53' Dry Van, 28,300 lb, Laundry detergent.",
        ],
        agent: {"reference":"PO-61907","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-21","pickup_appt":"06:00","delivery_facility":"Fairmont Grocers DC, Des Moines IA","delivery_appt":"07:00-12:00","equipment":"53' Dry Van","weight_lbs":28300,"stops":["Milwaukee WI","Des Moines IA"],"commodity":"Laundry detergent"},
        rep: {"reference":"PO-61907","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/21/2026","pickup_appt":"0600","delivery_facility":"FAIRMONT GROCERS DC, DES MOINES IA","delivery_appt":"0700-1200","equipment":"53' DRY VAN","weight_lbs":28300,"stops":["MILWAUKEE WI","DES MOINES IA"],"commodity":"LAUNDRY DETERGENT"},
      },
      {
        load_id: "E-08", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/21",
          "Body: Please pick up 9/21 at 10:00 CT from Shipper E Warehouse, Milwaukee WI. PO 61908.",
          "Deliver to Northline Hardware DC, Madison WI, appt 14:30 CT.",
          "53' Dry Van, 23,100 lb, Paper towels.",
        ],
        agent: {"reference":"PO-61908","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-21","pickup_appt":"10:00","delivery_facility":"Northline Hardware DC, Madison WI","delivery_appt":"14:30","equipment":"53' Dry Van","weight_lbs":23100,"stops":["Milwaukee WI","Madison WI"],"commodity":"Paper towels"},
        rep: {"reference":"PO-61908 ","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/21/2026","pickup_appt":"1000","delivery_facility":"NORTHLINE HARDWARE DC, MADISON WI","delivery_appt":"1430","equipment":"53' DRY VAN","weight_lbs":23100,"stops":["MILWAUKEE WI","MADISON WI"],"commodity":"PAPER TOWELS"},
      },
      {
        load_id: "E-09", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/22",
          "Body: Please pick up 9/22 at 06:30 CT from Shipper E Warehouse, Milwaukee WI. PO 61909.",
          "Deliver to Granite Peak Outfitters DC, Minneapolis MN, appt 15:30 CT. Stops in order: Oshkosh WI, Eau Claire WI, then Minneapolis MN.",
          "53' Dry Van, 34,700 lb, Bottled water.",
        ],
        agent: {"reference":"PO-61909","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-22","pickup_appt":"06:30","delivery_facility":"Granite Peak Outfitters DC, Minneapolis MN","delivery_appt":"15:30","equipment":"53' Dry Van","weight_lbs":34700,"stops":["Milwaukee WI","Oshkosh WI","Eau Claire WI","Minneapolis MN"],"commodity":"Bottled water"},
        rep: {"reference":"PO-61909","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/22/2026","pickup_appt":"0630","delivery_facility":"GRANITE PEAK OUTFITTERS DC, MINNEAPOLIS MN","delivery_appt":"1530","equipment":"53' DRY VAN","weight_lbs":34700,"stops":["MILWAUKEE WI","OSHKOSH WI","EAU CLAIRE WI","MINNEAPOLIS MN"],"commodity":"BOTTLED WATER"},
      },
      {
        load_id: "E-10", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/23",
          "Body: Please pick up 9/23 at 08:00 CT from Shipper E Warehouse, Milwaukee WI. PO 61910.",
          "Deliver to Prairie Pantry DC, Omaha NE, appt 12:00 CT.",
          "53' Dry Van, 31,600 lb, Bottled water.",
        ],
        agent: {"reference":"PO-61910","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-23","pickup_appt":"08:00","delivery_facility":"Prairie Pantry DC, Omaha NE","delivery_appt":"12:00","equipment":"53' Dry Van","weight_lbs":31600,"stops":["Milwaukee WI","Omaha NE"],"commodity":"Bottled water"},
        rep: {"reference":"PO-61910","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/23/2026","pickup_appt":"0800","delivery_facility":"PRAIRIE PANTRY DC, OMAHA NE","delivery_appt":"1200","equipment":"53' DRY VAN","weight_lbs":31600,"stops":["MILWAUKEE WI","OMAHA NE"],"commodity":"WATER BTLD"},
      },
      {
        load_id: "E-11", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/24",
          "Body: Please pick up 9/24 at 07:00 CT from Shipper E Warehouse, Milwaukee WI. PO 61911.",
          "Deliver to Fairmont Grocers DC, Des Moines IA, window 08:00-13:00 CT.",
          "53' Dry Van, 27,800 lb, Paper towels.",
        ],
        agent: {"reference":"PO-61911","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-24","pickup_appt":"07:00","delivery_facility":"Fairmont Grocers DC, Des Moines IA","delivery_appt":"08:00-13:00","equipment":"53' Dry Van","weight_lbs":27800,"stops":["Milwaukee WI","Des Moines IA"],"commodity":"Paper towels"},
        rep: {"reference":"PO-61911","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/24/2026","pickup_appt":"0700","delivery_facility":"FAIRMONT GROCERS DC, DES MOINES IA","delivery_appt":"0800-1300","equipment":"53' DRY VAN","weight_lbs":27800,"stops":["MILWAUKEE WI","DES MOINES IA"],"commodity":"PAPER TOWELS"},
      },
      {
        load_id: "E-12", shipper: "E", source_format: "Email",
        source: [
          "Subject: New load for 9/25",
          "Body: Please pick up 9/25 at 05:00 CT from Shipper E Warehouse, Milwaukee WI. PO 61912.",
          "Deliver to Granite Peak Outfitters DC, Minneapolis MN, appt 14:00 CT. Stops in order: Madison WI, Rochester MN, then Minneapolis MN.",
          "53' Dry Van, 33,300 lb, Laundry detergent.",
        ],
        agent: {"reference":"PO-61912","pickup_facility":"Shipper E Warehouse, Milwaukee WI","pickup_date":"2026-09-25","pickup_appt":"05:00","delivery_facility":"Granite Peak Outfitters DC, Minneapolis MN","delivery_appt":"14:00","equipment":"53' Dry Van","weight_lbs":33300,"stops":["Milwaukee WI","Madison WI","Rochester MN","Minneapolis MN"],"commodity":"Laundry detergent"},
        rep: {"reference":"PO-61912 ","pickup_facility":"SHIPPER E WAREHOUSE, MILWAUKEE WI","pickup_date":"09/25/2026","pickup_appt":"0500","delivery_facility":"GRANITE PEAK OUTFITTERS DC, MINNEAPOLIS MN","delivery_appt":"1400","equipment":"53' DRY VAN","weight_lbs":33300,"stops":["MILWAUKEE WI","MADISON WI","ROCHESTER MN","MINNEAPOLIS MN"],"commodity":"LAUNDRY DETERGENT"},
      },
      {
        load_id: "F-01", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 2",
          "PO 77111 | Pickup 09/14/2026 07:00 CT | Shipper F Plant, Dallas TX",
          "Deliver Bayou Fabrication, Houston TX | appt 13:00 CT",
          "48' Flatbed | Weight 44000 | Unit LB | Steel coil",
        ],
        agent: {"reference":"PO-77111","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-14","pickup_appt":"07:00","delivery_facility":"Bayou Fabrication, Houston TX","delivery_appt":"13:00","equipment":"48' Flatbed","weight_lbs":44000,"stops":["Dallas TX","Houston TX"],"commodity":"Steel coil"},
        rep: {"reference":"PO-77111","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/14/2026","pickup_appt":"0700","delivery_facility":"BAYOU FABRICATION, HOUSTON TX","delivery_appt":"1300","equipment":"48' FLATBED","weight_lbs":44000,"stops":["DALLAS TX","HOUSTON TX"],"commodity":"STEEL COIL"},
      },
      {
        load_id: "F-02", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 3",
          "PO 77112 | Pickup 09/14/2026 08:00 CT | Shipper F Plant, Dallas TX",
          "Deliver Red River Builders Supply, Oklahoma City OK | window 07:00-12:00 CT",
          "48' Flatbed | Weight 18000 | Unit KG | Rebar",
        ],
        agent: {"reference":"PO-77112","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-14","pickup_appt":"08:00","delivery_facility":"Red River Builders Supply, Oklahoma City OK","delivery_appt":"07:00-12:00","equipment":"48' Flatbed","weight_lbs":18000,"stops":["Dallas TX","Oklahoma City OK"],"commodity":"Rebar"},
        rep: {"reference":"PO-77112","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/14/2026","pickup_appt":"0800","delivery_facility":"RED RIVER BUILDERS SUPPLY, OKLAHOMA CITY OK","delivery_appt":"0700-1200","equipment":"48' FLATBED","weight_lbs":39683,"stops":["DALLAS TX","OKLAHOMA CITY OK"],"commodity":"REBAR"},
      },
      {
        load_id: "F-03", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 4",
          "PO 77113 | Pickup 09/15/2026 06:00 CT | Shipper F Plant, Dallas TX",
          "Deliver Ozark Metal Works, Little Rock AR | appt 14:00 CT",
          "48' Flatbed | Weight 42600 | Unit LB | Steel pipe",
        ],
        agent: {"reference":"PO-77113","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-15","pickup_appt":"06:00","delivery_facility":"Ozark Metal Works, Little Rock AR","delivery_appt":"14:00","equipment":"48' Flatbed","weight_lbs":42600,"stops":["Dallas TX","Little Rock AR"],"commodity":"Steel pipe"},
        rep: {"reference":"PO-77113","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/15/2026","pickup_appt":"0600","delivery_facility":"OZARK METAL WORKS, LITTLE ROCK AR","delivery_appt":"1400","equipment":"48' FLATBED","weight_lbs":42600,"stops":["DALLAS TX","LITTLE ROCK AR"],"commodity":"STEEL PIPE"},
      },
      {
        load_id: "F-04", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 5",
          "PO 77114 | Pickup 09/16/2026 09:00 CT | Shipper F Plant, Dallas TX",
          "Deliver Bayou Fabrication, Houston TX | appt 15:00 CT",
          "48' Flatbed | Weight 43100 | Unit LB | Rebar",
        ],
        agent: {"reference":"PO-77114","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-16","pickup_appt":"09:00","delivery_facility":"Bayou Fabrication, Houston TX","delivery_appt":"15:00","equipment":"48' Flatbed","weight_lbs":43100,"stops":["Dallas TX","Houston TX"],"commodity":"Rebar"},
        rep: {"reference":"PO-77114 ","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/16/2026","pickup_appt":"0900","delivery_facility":"BAYOU FABRICATION, HOUSTON TX","delivery_appt":"1500","equipment":"48' FLATBED","weight_lbs":43100,"stops":["DALLAS TX","HOUSTON TX"],"commodity":"REBAR"},
      },
      {
        load_id: "F-05", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 6",
          "PO 77115 | Pickup 09/17/2026 07:30 CT | Shipper F Plant, Dallas TX",
          "Deliver Red River Builders Supply, Oklahoma City OK | window 08:00-13:00 CT",
          "48' Flatbed | Weight 19500 | Unit KG | Steel coil",
        ],
        agent: {"reference":"PO-77115","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-17","pickup_appt":"07:30","delivery_facility":"Red River Builders Supply, Oklahoma City OK","delivery_appt":"08:00-13:00","equipment":"48' Flatbed","weight_lbs":19500,"stops":["Dallas TX","Oklahoma City OK"],"commodity":"Steel coil"},
        rep: {"reference":"PO-77115","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/17/2026","pickup_appt":"0730","delivery_facility":"RED RIVER BUILDERS SUPPLY, OKLAHOMA CITY OK","delivery_appt":"0800-1300","equipment":"48' FLATBED","weight_lbs":42990,"stops":["DALLAS TX","OKLAHOMA CITY OK"],"commodity":"STEEL COIL"},
      },
      {
        load_id: "F-06", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 7",
          "PO 77116 | Pickup 09/18/2026 06:30 CT | Shipper F Plant, Dallas TX",
          "Deliver Ozark Metal Works, Little Rock AR | appt 12:30 CT",
          "48' Flatbed | Weight 41800 | Unit LB | Steel pipe",
        ],
        agent: {"reference":"PO-77116","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-18","pickup_appt":"06:30","delivery_facility":"Ozark Metal Works, Little Rock AR","delivery_appt":"12:30","equipment":"48' Flatbed","weight_lbs":41800,"stops":["Dallas TX","Little Rock AR"],"commodity":"Steel pipe"},
        rep: {"reference":"PO-77116","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/18/2026","pickup_appt":"0630","delivery_facility":"OZARK METAL WORKS, LITTLE ROCK AR","delivery_appt":"1230","equipment":"48' FLATBED","weight_lbs":41800,"stops":["DALLAS TX","LITTLE ROCK AR"],"commodity":"STEEL PIPE"},
      },
      {
        load_id: "F-07", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 8",
          "PO 77117 | Pickup 09/21/2026 08:00 CT | Shipper F Plant, Dallas TX",
          "Deliver Bayou Fabrication, Houston TX | window 06:00-11:00 CT",
          "48' Flatbed | Weight 44000 | Unit LB | Steel coil",
        ],
        agent: {"reference":"PO-77117","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-21","pickup_appt":"08:00","delivery_facility":"Bayou Fabrication, Houston TX","delivery_appt":"06:00-11:00","equipment":"48' Flatbed","weight_lbs":44000,"stops":["Dallas TX","Houston TX"],"commodity":"Steel coil"},
        rep: {"reference":"PO-77117","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/21/2026","pickup_appt":"0800","delivery_facility":"BAYOU FABRICATION, HOUSTON TX","delivery_appt":"0600-1100","equipment":"48' FLATBED","weight_lbs":44000,"stops":["DALLAS TX","HOUSTON TX"],"commodity":"STEEL COIL"},
      },
      {
        load_id: "F-08", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 9",
          "PO 77118 | Pickup 09/21/2026 10:00 CT | Shipper F Plant, Dallas TX",
          "Deliver Red River Builders Supply, Oklahoma City OK | appt 16:00 CT",
          "48' Flatbed | Weight 17250 | Unit KG | Steel pipe",
        ],
        agent: {"reference":"PO-77118","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-21","pickup_appt":"10:00","delivery_facility":"Red River Builders Supply, Oklahoma City OK","delivery_appt":"16:00","equipment":"48' Flatbed","weight_lbs":17250,"stops":["Dallas TX","Oklahoma City OK"],"commodity":"Steel pipe"},
        rep: {"reference":"PO-77118 ","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/21/2026","pickup_appt":"1000","delivery_facility":"RED RIVER BUILDERS SUPPLY, OKLAHOMA CITY OK","delivery_appt":"1600","equipment":"48' FLATBED","weight_lbs":38030,"stops":["DALLAS TX","OKLAHOMA CITY OK"],"commodity":"STEEL PIPE"},
      },
      {
        load_id: "F-09", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 10",
          "PO 77119 | Pickup 09/22/2026 07:00 CT | Shipper F Plant, Dallas TX",
          "Deliver Ozark Metal Works, Little Rock AR | appt 13:00 CT",
          "48' Flatbed | Weight 42900 | Unit LB | Rebar",
        ],
        agent: {"reference":"PO-77119","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-22","pickup_appt":"07:00","delivery_facility":"Ozark Metal Works, Little Rock AR","delivery_appt":"13:00","equipment":"48' Flatbed","weight_lbs":42900,"stops":["Dallas TX","Little Rock AR"],"commodity":"Rebar"},
        rep: {"reference":"PO-77119","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/22/2026","pickup_appt":"0700","delivery_facility":"OZARK METAL WORKS, LITTLE ROCK AR","delivery_appt":"1300","equipment":"48' FLATBED","weight_lbs":42900,"stops":["DALLAS TX","LITTLE ROCK AR"],"commodity":"REBAR"},
      },
      {
        load_id: "F-10", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 11",
          "PO 77120 | Pickup 09/23/2026 06:00 CT | Shipper F Plant, Dallas TX",
          "Deliver Bayou Fabrication, Houston TX | appt 14:00 CT",
          "48' Flatbed | Weight 43700 | Unit LB | Steel pipe",
        ],
        agent: {"reference":"PO-77120","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-23","pickup_appt":"06:00","delivery_facility":"Bayou Fabrication, Houston TX","delivery_appt":"14:00","equipment":"48' Flatbed","weight_lbs":43700,"stops":["Dallas TX","Houston TX"],"commodity":"Steel pipe"},
        rep: {"reference":"PO-77120","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/23/2026","pickup_appt":"0600","delivery_facility":"BAYOU FABRICATION, HOUSTON TX","delivery_appt":"1400","equipment":"48' FLATBED","weight_lbs":43700,"stops":["DALLAS TX","HOUSTON TX"],"commodity":"STEEL PIPE"},
      },
      {
        load_id: "F-11", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 12",
          "PO 77121 | Pickup 09/24/2026 09:30 CT | Shipper F Plant, Dallas TX",
          "Deliver Red River Builders Supply, Oklahoma City OK | window 07:00-11:00 CT",
          "48' Flatbed | Weight 18800 | Unit KG | Rebar",
        ],
        agent: {"reference":"PO-77121","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-24","pickup_appt":"09:30","delivery_facility":"Red River Builders Supply, Oklahoma City OK","delivery_appt":"07:00-11:00","equipment":"48' Flatbed","weight_lbs":18800,"stops":["Dallas TX","Oklahoma City OK"],"commodity":"Rebar"},
        rep: {"reference":"PO-77121","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/24/2026","pickup_appt":"0930","delivery_facility":"RED RIVER BUILDERS SUPPLY, OKLAHOMA CITY OK","delivery_appt":"0700-1100","equipment":"48' FLATBED","weight_lbs":41447,"stops":["DALLAS TX","OKLAHOMA CITY OK"],"commodity":"REBAR"},
      },
      {
        load_id: "F-12", shipper: "F", source_format: "Spreadsheet",
        source: [
          "Sheet \"Tenders\", row 13",
          "PO 77122 | Pickup 09/25/2026 08:00 CT | Shipper F Plant, Dallas TX",
          "Deliver Ozark Metal Works, Little Rock AR | appt 15:00 CT",
          "48' Flatbed | Weight 41500 | Unit LB | Steel coil",
        ],
        agent: {"reference":"PO-77122","pickup_facility":"Shipper F Plant, Dallas TX","pickup_date":"2026-09-25","pickup_appt":"08:00","delivery_facility":"Ozark Metal Works, Little Rock AR","delivery_appt":"15:00","equipment":"48' Flatbed","weight_lbs":41500,"stops":["Dallas TX","Little Rock AR"],"commodity":"Steel coil"},
        rep: {"reference":"PO-77122 ","pickup_facility":"SHIPPER F PLANT, DALLAS TX","pickup_date":"09/25/2026","pickup_appt":"0800","delivery_facility":"OZARK METAL WORKS, LITTLE ROCK AR","delivery_appt":"1500","equipment":"48' FLATBED","weight_lbs":41500,"stops":["DALLAS TX","LITTLE ROCK AR"],"commodity":"STEEL COIL"},
      },
    ],
  };
  root.SHADOW_RUN_DATA = SHADOW_RUN_DATA;
})(globalThis);
